# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE = "generic/debian10"
BRIDGE = "wlp4s0"
CPUS = 1
MEMORY = 512

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.hostname = "debian"
  config.vm.network :public_network, bridge: BRIDGE
  config.vm.provider "virtualbox" do |v|
    v.name = "Debian-10"
    v.cpus = CPUS
    v.memory = MEMORY
  end
end