# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE = "plaurin/solaris-11_3"
BRIDGE = "wlp4s0"
CPUS = 1
MEMORY = 1024

Vagrant.configure("2") do |config|
  config.ssh.password = "1vagrant"
  config.vm.box = IMAGE
  config.vm.hostname = "solaris"
  config.vm.network :public_network, bridge: BRIDGE
  config.vm.provider "virtualbox" do |v|
    v.name = "Solaris-11.3_64"
    v.cpus = CPUS
    v.memory = MEMORY
    v.linked_clone = false
  end
end
