# -*- mode: ruby -*-
# vi: set ft=ruby :

UBUNTU_NODE_COUNT = 1
UBUNTU_IMAGE = "ubuntu/bionic64"
BRIDGE = "wlp4s0"
CPUS = 1
MEMORY = 512

Vagrant.configure("2") do |config|
config.vbguest.auto_update = false
#config.vbguest.iso_path = "/home/user/vagrant/VBoxGuestAdditions_5.2.8.iso"
#config.disksize.size = '8GB'
config.ssh.insert_key = false
#config.vm.synced_folder ".", "/home/vagrant", type: "nfs"

(1..UBUNTU_NODE_COUNT).each do |i|
config.vm.define "bionic#{i}" do |node|
  node.vm.box = UBUNTU_IMAGE
  node.vm.hostname = "bionic#{i}"
  #node.vm.network :public_network, bridge: BRIDGE
  node.vm.network :private_network, ip: "192.168.88.1#{i}"
  #node.vm.network :forwarded_port, guest: 80, host: "808#{i}"
  config.vm.provider :virtualbox do |vb|
    vb.name = "bionic#{i}"
    vb.cpus = CPUS
    vb.memory = MEMORY
    vb.linked_clone = true
  end
  config.vm.provision "shell" do |s|
    ansible_pub_key = File.readlines("#{Dir.home}/.ssh/ansible_id_rsa.pub").first.strip
    s.inline = <<-SHELL
      #echo #{ansible_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ansible_pub_key} >> /home/ubuntu/.ssh/authorized_keys
      mkdir -p /root/.ssh && chmod 0700 /root/.ssh && echo #{ansible_pub_key} >> /root/.ssh/authorized_keys && chmod 0600 /root/.ssh/authorized_keys
    SHELL
  end
  #config.vm.provision "ansible" do |ansible|
  #  ansible.limit = "manager"
  #  ansible.playbook = "/home/user/ansible/playbooks/server/step0/manage/docker-swarm.yml"
  #end
end
end

end
