# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Freebsd12"
  config.vm.network :public_network, bridge: "wlp4s0",
    use_dhcp_assigned_default_route: true
end
