# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE = "Freebsd12"
BRIDGE = "wlp4s0"
CPUS = 1
MEMORY = 1024

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.hostname = "freebsd"
  config.vm.network :public_network, bridge: BRIDGE
  config.vm.provider "virtualbox" do |v|
    v.name = "Freebsd-12_64"
    v.cpus = CPUS
    v.memory = MEMORY
  end
end
