# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "Freebsd12"
  config.vm.hostname = "freebsd"
  config.vm.network :public_network, bridge: "wlp4s0"
  config.vm.provider "virtualbox" do |v|
    v.name = "Freebsd-12_64"
  end
end

