# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 2
IMAGE = "generic/ubuntu1804"
BRIDGE = "wlp4s0"
CPUS = 1
MEMORY = 512

Vagrant.configure("2") do |config|
config.ssh.insert_key = false
config.vm.synced_folder ".", "/vagrant", disabled: true

(0..NODE_COUNT - 1).each do |i|
config.vm.define "ubuntu-test#{i + 1}" do |node|
  node.vm.hostname = "ubuntu-test#{i + 1}"
  node.vm.box = IMAGE
  node.vm.network :public_network, bridge: BRIDGE
  config.vm.provider :virtualbox do |vb|
    vb.name = "ubuntu-test#{i + 1}"
    vb.cpus = CPUS
    vb.memory = MEMORY
  end
end
end
end
