# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ansible/tower"
  config.vm.hostname = "ansible"
  config.vm.network :public_network, bridge: "wlp4s0"
  config.vm.provider "virtualbox" do |v|
    v.name = "Ansible"
  end
end
