# -*- mode: ruby -*-
# vi: set ft=ruby :

IMAGE = "centos/7"
BRIDGE = "wlp4s0"
CPUS = 1
MEMORY = 512

Vagrant.configure("2") do |config|
  config.vm.box = IMAGE
  config.vm.hostname = "centos"
  config.vm.network :public_network, bridge: BRIDGE
  config.vm.provider "virtualbox" do |v|
    v.name = "Centos-7_64"
    v.cpus = CPUS
    v.memory = MEMORY
  end
end
