# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "centos"
  config.vm.network :public_network, bridge: "wlp4s0"
  config.vm.provider "virtualbox" do |v|
    v.name = "Centos-7_64"
  end
end
